Repository acm-ucr/projects, pull requests merged in 2024-01, with the labels that each got.

#18 Add Navigation SideBar
  package-lock.json
  src/components/Navigation.jsx
Labels: Ready for Review

#21 Added input component
  src/components/Input.jsx
Labels: Repository

#12 Added profile header
  public/images/pfp.webp
  src/components/developer/profile/Header.jsx
Labels: Ready for Review

#20 Created Title component (unsure about margins)
  src/components/Title.jsx
Labels: Repository

#30 Added nav header and fixed other nav stuff
  public/images/acm-ucr-logo.webp
  src/components/Navigation.jsx
Labels: Profile

#31 Created a custom button component #25
  src/components/Button.jsx
Labels: Ready for Review
